//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audit.EntityFramework.Edmx.UnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditBlog
    {
        public int Id { get; set; }
        public int BlogId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Changes { get; set; }
    }
}
