//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audit.EntityFramework.UnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Post
    {
        public int Id { get; set; }
        public string PostId { get; set; }
        public string Text { get; set; }
        public string AuditAction { get; set; }
        public string AuditDate { get; set; }
    }
}
