//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audit.EntityFramework.UnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public long EventId { get; set; }
        public System.DateTimeOffset InsertedDate { get; set; }
        public System.DateTimeOffset LastUpdatedDate { get; set; }
        public string Data { get; set; }
    }
}
