using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Audit.Core;
using Audit.Elasticsearch.Providers;
using Audit.IntegrationTest;

using Elastic.Clients.Elasticsearch;

using NUnit.Framework;

namespace Audit.Elasticsearch.UnitTest
{
    public class ElasticsearchTests
    {
        private const string TestIndexName = "auditevent_test";
        private const string TestIndexName2 = "auditevent_test2";

        [SetUp]
        public void Setup()
        {
            Audit.Core.Configuration.Reset();
        }

        [Test]
        public void Test_ElasticSearchDataProvider_FluentApi()
        {
            var x = new Elasticsearch.Providers.ElasticsearchDataProvider(_ => _
                .Client(new ElasticsearchClientSettings(new Uri("http://server/")))
                .Id(ev => "id")
                .Index("ix"));

            Assert.That((x.Settings.NodePool.Nodes.First().Uri.ToString()), Is.EqualTo("http://server/"));
            Assert.That(x.IdBuilder.Invoke(null).Equals(new Id("id")), Is.True);
            Assert.That(x.Index.GetDefault(), Is.EqualTo((IndexName)"ix"));
        }

        [Test]
        public void Test_UseElasticsearch_Extension()
        {
            Audit.Core.Configuration.Setup()
                .UseElasticsearch(cfg => cfg
                    .Client(new ElasticsearchClientSettings(new Uri("http://server/")))
                    .Index("ix"));

            Assert.That(Audit.Core.Configuration.DataProvider, Is.TypeOf<ElasticsearchDataProvider>());
        }

        [Test]
        [Category(TestCommon.Category.Integration)]
        [Category(TestCommon.Category.Elasticsearch)]
        public void Test_Elasticsearch_HappyPath()
        {
            var dataProvider = new ElasticsearchDataProvider(new ElasticsearchClient(new Uri(TestCommon.ElasticSearchUrl)));
            var indexName = TestIndexName2;
            
            var guids = new List<string>();
            dataProvider.Index = (IndexName)indexName;
            dataProvider.IdBuilder = ev => { var g = Guid.NewGuid().ToString(); guids.Add(g); return g; };

            Audit.Core.Configuration.Setup()
                .UseCustomProvider(dataProvider)
                .WithCreationPolicy(EventCreationPolicy.InsertOnStartReplaceOnEnd)
                .ResetActions();

            var order = new Order()
            {
                Id = 1,
                Status = "Created"
            };
            
            using (var scope = new AuditScopeFactory().Create("eventType", () => order, new { MyCustomField = "value" }, null, null))
            {
                order.Status = "Updated";
            }

            var evLoad = dataProvider.GetEvent(new ElasticsearchAuditEventId() { Id = guids[0], Index = indexName });
            
            Assert.That(evLoad, Is.Not.Null);
            Assert.That(guids.Count, Is.EqualTo(1));
            Assert.That(evLoad.CustomFields["MyCustomField"].ToString(), Is.EqualTo("value"));
        }

        [Test]
        [Category(TestCommon.Category.Integration)]
        [Category(TestCommon.Category.Elasticsearch)]
        public async Task Test_Elasticsearch_HappyPath_Async()
        {
            var dataProvider = new ElasticsearchDataProvider(c => c.Client(new ElasticsearchClientSettings(new Uri(TestCommon.ElasticSearchUrl))));
            var indexName = TestIndexName2;

            var guids = new List<string>();
            dataProvider.Index = (IndexName)indexName;
            dataProvider.IdBuilder = ev => { var g = Guid.NewGuid().ToString(); guids.Add(g); return g; };

            Audit.Core.Configuration.Setup()
                .UseCustomProvider(dataProvider)
                .WithCreationPolicy(Core.EventCreationPolicy.InsertOnStartReplaceOnEnd)
                .ResetActions();

            var order = new Order()
            {
                Id = 1,
                Status = "Created"
            };

            using (var scope = await new AuditScopeFactory().CreateAsync("eventType", () => order, new { MyCustomField = "value" }, null, null))
            {
                order.Status = "Updated";
            }

            var evLoad = await dataProvider.GetEventAsync(new ElasticsearchAuditEventId() { Id = guids[0], Index = indexName });

            Assert.That(evLoad, Is.Not.Null);
            Assert.That(guids.Count, Is.EqualTo(1));
            Assert.That(evLoad.CustomFields["MyCustomField"].ToString(), Is.EqualTo("value"));
        }

        [Test]
        [Category(TestCommon.Category.Integration)]
        [Category(TestCommon.Category.Elasticsearch)]
        public void Test_Elasticsearch_AutoGeneratedId()
        {
            var dataProvider = new ElasticsearchDataProvider(c => c.Client(new ElasticsearchClient(new ElasticsearchClientSettings(new Uri(TestCommon.ElasticSearchUrl)))));
            var indexName = TestIndexName;

            dataProvider.Index = (IndexName)indexName;
            dataProvider.IdBuilder = ev => null;

            Audit.Core.Configuration.Setup()
                .UseCustomProvider(dataProvider)
                .WithCreationPolicy(Core.EventCreationPolicy.InsertOnStartReplaceOnEnd)
                .ResetActions();

            var sb = "init";

            ElasticsearchAuditEventId id;
            using (var scope = new AuditScopeFactory().Create("eventType", () => sb, new { MyCustomField = "value" }, null, null))
            {
                id = (ElasticsearchAuditEventId)scope.EventId;
                sb += "-end";
            }

            var evResult = dataProvider.GetEvent(id);
            
            Assert.That(evResult, Is.Not.Null);
            Assert.That(evResult.Target.Old.ToString(), Is.EqualTo("init"));
            Assert.That(evResult.Target.New.ToString(), Is.EqualTo("init-end"));
            Assert.That(evResult.CustomFields["MyCustomField"]?.ToString(), Is.EqualTo("value"));
        }

        [Test]
        [Category(TestCommon.Category.Integration)]
        [Category(TestCommon.Category.Elasticsearch)]
        public async Task Test_Elasticsearch_AutoGeneratedId_Async()
        {
            var dataProvider = new ElasticsearchDataProvider(c => c.Client(new Uri(TestCommon.ElasticSearchUrl)));
            var indexName = TestIndexName;

            dataProvider.Index = (IndexName)indexName;
            dataProvider.IdBuilder = ev => null;

            Audit.Core.Configuration.Setup()
                .UseCustomProvider(dataProvider)
                .WithCreationPolicy(Core.EventCreationPolicy.InsertOnStartReplaceOnEnd)
                .ResetActions();

            var sb = "init";

            ElasticsearchAuditEventId id;
            using (var scope = await new AuditScopeFactory().CreateAsync("eventType", () => sb, new { MyCustomField = "value" }, null, null))
            {
                id = (ElasticsearchAuditEventId)scope.EventId;
                sb += "-end";
            }

            var evResult = await dataProvider.GetEventAsync(id);

            Assert.That(evResult, Is.Not.Null);
            Assert.That(evResult.Target.Old.ToString(), Is.EqualTo("init"));
            Assert.That(evResult.Target.New.ToString(), Is.EqualTo("init-end"));
            Assert.That(evResult.CustomFields["MyCustomField"]?.ToString(), Is.EqualTo("value"));
        }

        [Test]
        [Category(TestCommon.Category.Integration)]
        [Category(TestCommon.Category.Elasticsearch)]
        public void Test_Elasticsearch_Polymorphic_Serialization()
        {
            var indexName = TestIndexName;
            var dp = new ElasticsearchDataProvider(c => c.Client(new Uri(TestCommon.ElasticSearchUrl)).Index(indexName));

            Audit.Core.Configuration.Setup().UseNullProvider();

            var ev = new CustomAuditEvent()
            {
                CustomProperty = "test"
            };

            var scope = AuditScope.Create(new AuditScopeOptions() { AuditEvent = ev });
            scope.SetCustomField("CustomField", "value");
            scope.Discard();

            var id = dp.InsertEvent(ev) as ElasticsearchAuditEventId;

            var result = dp.GetEvent<CustomAuditEvent>(id);

            Assert.That(result, Is.Not.Null);
            Assert.That(result.CustomFields.Count, Is.EqualTo(1));
            Assert.That(result.CustomFields["CustomField"].ToString(), Is.EqualTo("value"));
            Assert.That(result.CustomProperty, Is.EqualTo("test"));
        }

        [Test]
        [Category(TestCommon.Category.Integration)]
        [Category(TestCommon.Category.Elasticsearch)]
        public async Task Test_Elasticsearch_Polymorphic_SerializationAsync()
        {
            var indexName = TestIndexName;
            var dp = new ElasticsearchDataProvider(c => c.Client(new Uri(TestCommon.ElasticSearchUrl)).Index(indexName));

            Audit.Core.Configuration.Setup().UseNullProvider();

            var ev = new CustomAuditEvent()
            {
                CustomProperty = "test"
            };

            var scope = await AuditScope.CreateAsync(new AuditScopeOptions() { AuditEvent = ev });
            scope.SetCustomField("CustomField", "value");
            scope.Discard();

            var id = (await dp.InsertEventAsync(ev)) as ElasticsearchAuditEventId;
            ev.CustomProperty = "updated";
            await dp.ReplaceEventAsync(id, ev);

            var result = await dp.GetEventAsync<CustomAuditEvent>(id);

            Assert.That(result, Is.Not.Null);
            Assert.That(result.CustomFields.Count, Is.EqualTo(1));
            Assert.That(result.CustomFields["CustomField"].ToString(), Is.EqualTo("value"));
            Assert.That(result.CustomProperty, Is.EqualTo("updated"));
        }
    }

    public class CustomAuditEvent : AuditEvent
    {
        public string CustomProperty { get; set; }
    }

    public class Order
    {
        public virtual long Id { get; set; }
        public virtual string Number { get; set; }
        public virtual string Status { get; set; }
    }
}
