using Audit.Core;

using Microsoft.Azure.Functions.Worker;

using System;
using System.Collections.Generic;

namespace Audit.AzureFunctions.ConfigurationApi;

public interface IAuditAzureFunctionConfigurator
{
    /// <summary>
    /// The options being configured.
    /// </summary>
    AuditAzureFunctionOptions Options { get; }

    /// <summary>
    /// Sets a predicate to determine if an Azure Function call should be audited.
    /// Return true to audit, false to skip. Default is to audit all calls.
    /// </summary>
    /// <param name="callFilter">Predicate evaluated per call.</param>
    /// <returns>This configurator instance.</returns>
    IAuditAzureFunctionConfigurator AuditWhen(Func<FunctionContext, bool> callFilter);

    /// <summary>
    /// Determines whether to include the function definition in the audit event.
    /// </summary>
    /// <param name="includePredicate">Predicate to decide inclusion.</param>
    IAuditAzureFunctionConfigurator IncludeFunctionDefinition(Func<FunctionContext, bool> includePredicate);

    /// <summary>
    /// Determines whether to include the function definition in the audit event.
    /// </summary>
    /// <param name="include">If true, includes the function definition; otherwise, excludes it.</param>
    IAuditAzureFunctionConfigurator IncludeFunctionDefinition(bool include = true);

    /// <summary>
    /// Determines whether to include trigger information in the audit event.
    /// </summary>
    /// <param name="includePredicate">Predicate to decide inclusion.</param>
    IAuditAzureFunctionConfigurator IncludeTriggerInfo(Func<FunctionContext, bool> includePredicate);

    /// <summary>
    /// Specifies whether trigger information should be included in the audit event for the Azure Function.
    /// </summary>
    /// <param name="include">If true, includes the trigger information; otherwise, excludes it.</param>
    IAuditAzureFunctionConfigurator IncludeTriggerInfo(bool include = true);

    /// <summary>
    /// Sets a delegate that resolves the <see cref="IAuditDataProvider"/>.
    /// </summary>
    /// <param name="dataProvider">Delegate returning the data provider.</param>
    /// <returns>This configurator instance.</returns>
    IAuditAzureFunctionConfigurator DataProvider(Func<FunctionContext, IAuditDataProvider> dataProvider);

    /// <summary>
    /// Sets a fixed <see cref="IAuditDataProvider"/> for audit events.
    /// </summary>
    /// <param name="dataProvider">The data provider instance.</param>
    /// <returns>This configurator instance.</returns>
    IAuditAzureFunctionConfigurator DataProvider(IAuditDataProvider dataProvider);

    /// <summary>
    /// Sets the event creation policy to use for audits.
    /// </summary>
    /// <param name="eventCreationPolicy">The event creation policy.</param>
    /// <returns>This configurator instance.</returns>
    IAuditAzureFunctionConfigurator EventCreationPolicy(EventCreationPolicy eventCreationPolicy);

    /// <summary>
    /// Sets a delegate that returns additional custom fields to include in the audit event.
    /// </summary>
    /// <param name="customFields">Delegate returning a dictionary of custom fields.</param>
    IAuditAzureFunctionConfigurator WithCustomFields(Func<FunctionContext, Dictionary<string, object>> customFields);

    /// <summary>
    /// Configures a delegate that determines the event type for audit records generated by the Azure Function.
    /// Supports placeholders: {name} (function name) and {id} (function id). Defaults to "{name}".
    /// </summary>
    /// <remarks>Use this method to customize the event type based on the function execution context. The
    /// event type is typically used to categorize audit entries and may affect downstream processing or
    /// reporting.</remarks>
    /// <param name="eventType">A function that receives the current <see cref="FunctionContext"/> and returns a string representing the event
    /// type to be used in the audit log.</param>
    IAuditAzureFunctionConfigurator EventType(Func<FunctionContext, string> eventType);

    /// <summary>
    /// Specifies the event type to associate with the audit entry for the Azure Function.
    /// Supports placeholders: {name} (function name) and {id} (function id). Defaults to "{name}".
    /// </summary>
    /// <param name="eventType">The event type name to assign to the audit entry.</param>
    /// <returns>An instance of <see cref="IAuditAzureFunctionConfigurator"/> for further configuration.</returns>
    IAuditAzureFunctionConfigurator EventType(string eventType);
}